name: Verify

on:
  push:
    branches: [main, beta, chore/*, fix/*, feat/*]
  pull_request:
    types: [opened]
    branches: [main, beta]

jobs:
  action:
    name: Verify tests

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3

      - name: Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'

      - name: Use node_modules cache
        uses: actions/cache@v3
        id: modules-cache
        with:
          path: '**/node_modules'
          key: ${{ secrets.CACHE_VERSION }}-${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ secrets.CACHE_VERSION }}-${{ runner.os }}-modules-

      - name: Install dependencies
        if: steps.modules-cache.outputs.cache-hit != 'true'
        run: yarn install --immutable

      - name: Run tests
        run: yarn test
